= IsAttributePresent
:toc:
:toclevels: 5

== Introduction

Common attribute processors can be used directly to process attributes of a specific structure (the number and type of
arguments that an Attribute has). Many concrete Attribute processors in this library are just extensions of the common 
ones.

== `IsAttributePresent`

Processor: link:../../src/Common/IsAttributePresent.php[`IsAttributePresent`]

=== Methods

* `::detectForReflectionClass(ReflectionClass $reflectionClass, string $attributeFqn): bool`
+
Detects if the given reflection class has the `$attributeFqn` attribute.

* `::detectForReflectionProperty(ReflectionProperty $reflectionProperty, string $attributeFqn): bool`
+
Detects if the given reflection property has the `$attributeFqn` attribute.

=== Usage

==== Basic usage on a class property

[NOTE]
====
We are going to use `#[DoNotSerialize]` attribute to demonstrate.
====

Set `#[DoNotSerialize]` attribute on a property of your class.

[source,php]
----
class MyClass {
    #[DoNotSerialize]
    public int $myProperty;
}
----

In your custom serializer/normalizer use the `IsAttributePresent::detectForReflectionProperty()` to detect whether
the attribute is applied to a specific property and exclude it from your serialization/normalization result.

[source,php]
----
$shouldBeSerialized = IsAttributePresent::detectForReflectionProperty(
    reflectionProperty: new \ReflectionProperty(TargetClass::class, 'targetProperty'),
    attributeFqn: DoNotSerialize::class
);
----

==== Basic usage on a class

Set `#[DoNotSerialize]` attribute on a class.

[source,php]
----
#[DoNotSerialize]
class MyClass {
    public int $myProperty;
}
----

In your custom serializer/normalizer use the `IsAttributePresent::detectForreflectionClass()` to detect
whether the attribute is applied to the class that is used as a type of property. You can use Reflection to get the type
of your property. If it is, you can exclude that property from your serialization/normalization result.

[source,php]
----
$shouldBeSerialized = IsAttributePresent::detectForReflectionClass(
    reflectionClass: new \ReflectionClass(TargetClass::class),
    attrbuteFqn: DoNotSerialize::class
);
----

== Links

* link:../../available_attributes.adoc[Available Attributes]