= Changelog
:toc:
:toclevels: 5

== 2.0

=== 2.0.0

*Breaking changes:*

* Attribute processing methods were instantiating reflection objects (reflection classes, reflection properties, ...)
manually. This can have a negative performance impact. Attributes are natively processed in the reflection domain, so
their processors should have appropriate reflection objects as parameters;
* `PropertyValidator` is renamed to `ValidatePropertyProcessor` to follow the same naming convention as other attribute
processors;
* `DoNotSerializeDetector` is renamed to `DoNotSerializeProcessor`;

*Features:*

* Added `ValidatePropertyException`;

*Fixes:*

* `ValidatePropertyProcessor` is now throwing an exception when the property name is missing from array keys of the
validation arguments;
* Cleanup of unit tests;

*Documentation:*

* Updated documentation to reflect the changes;

== 1.1.

=== 1.1.1

*Features:*

* Added a common attribute processor for attributes that don't have any arguments;
* `#[DoNotSerialize]` attribute now uses the implemented common attribute processor;

*Documentation:*

* Documented common attribute processors;
* Adapted documentation of `#[DoNotSerialize]` attribute to reflect that it is now using a common attribute processor;
* Docblock comments are now added to all attributes to make it easier to see in IDE tooltips when hovering over an
attribute;
* Minor documentation typo fixes;

=== 1.1.0

*Features:*

* Added `transformReflectionProperty` to `TransformPropertyNameProcessor`;
* Added `transformReflectionProperty` to `TransformPropertyValueProcessor`;
* Library is now using https://github.com/constup-foss/php-exerr[constup-foss/php-exerr] for exceptions;

*Fixes:*

* Attribute processors that are using FCC transformation arguments are now throwing exceptions when the property name
is missing from array keys, but is expected.

*Documentation:*

* Added documentation for new features;
* Attribute processor documentation is now easier to read;

== 1.0

=== 1.0.3

* GitHub configuration;

=== 1.0.2

* `composer.json` fixes;

=== 1.0.1

* Documentation changes;

=== 1.0.0

*Attributes:*

* `#[DoNotSerialize]`;
* `#[TransformPropertyName]`;
* `#[TransformPropertyValue]`;
