= `#[DoNotSerialize]`
:toc:
:toclevels: 5

== Description

Use this attribute to mark a class or a class property for skipping during serialization/normalization. Can be used in
custom serializers or normalizers.

* Applicable to:
** Classes
** Class properties

* Arguments:
** none

* Repeatable: no

== Attribute Processors

=== `DoNotSerializeDetector`

Processor: link:../../../src/Serialization/DoNotSerialize/DoNotSerializeDetector.php[`DoNotSerializeDetector`]

* `::detectForClassOrObject(string|object $classOrObject): bool`
+
Runs link:../../common_attribute_processors/attribute_with_no_arguments_processor.adoc[AttributeWithNoArgumentsProcessor::detectForClassOrObject]
+
Detects if the given class or object has the `DoNotSerialize` attribute.
* `::detectForProperty(string|object $classOrObject, string $propertyName): bool`
+
Runs link:../../common_attribute_processors/attribute_with_no_arguments_processor.adoc[AttributeWithNoArgumentsProcessor::detectForProperty]
+
Detects if the given property of a class or object has the `DoNotSerialize` attribute.

== Links

* link:../../available_attributes.adoc[Available Attributes]