= `#[TransformPropertyValue]`
:toc:
:toclevels: 5

== Description

Use this attribute to transform the value of your property.

* Applicable to:
** Class properties

* Arguments
** `Closure $transformer` - link:https://wiki.php.net/rfc/fcc_in_const_expr[First Class Callable (PHP RFC Wiki link)].
Note that this attribute only supports using static methods.

* Repeatable: no

== Attribute Processors

=== `TransformPropertyValueProcessor`

Processor: link:../../../src/Serialization/TransformPropertyValue/TransformPropertyValueProcessor.php[`TransformPropertyValueProcessor`]

==== Methods

The following methods return a transformed version of `$propertyValue` by running the closure defined in the attribute.
If the attribute is not present, the original `$propertyValue` is returned. The only difference between them is their
arguments:

* `::transform(mixed $propertyValue, string $className, string $propertyName, array $transformationArguments = []): mixed`
+
Use it when you have a property value, class name and property name available when calling.
* `::transformFromObject(object $object, string $propertyName, array $transformationArguments = []): mixed`
+
Use it when you have an object and property name when calling.
* `::transformReflectionProperty(object $object, ReflectionProperty $reflectionProperty, array $transformationArguments = []): mixed`
+
Use it when you have an object and a reflection property when calling.

Note that the closure is run with the `$propertyValue` as the first argument, followed by `$transformationArguments`.
This effectively means that your static method that does the transformation must have the property value as its first
argument.

`$transformationArguments` is an associative array of additional transformation arguments. Index is the name of the
property the attribute is being applied to. Value is an array of arguments to be passed to the transformation closure
after the property value. If the property name is not present as the array key, but is expected, an exception is thrown.

==== Usage

===== Basic example

Apply the attribute to a property:

[source,php]
----
#[TransformPropertyValue(YourNameTransformingClass::yourStaticMethod(...))]
public int $yourProperty;
----

When you need to transform the value of your property, call:

[source, php]
----
$transformedPropertyValue = TransformPropertyValueProcessor::transform(
    propertyValue: $yourPropertyValue,
    className: YourClass::class,
    propertyName: 'yourPropertyName',
    transformationArguments: ['yourPropertyName' => [$arrayOfArguments, $neededByYourStaticMethod]]
);
----

or:

[source,php]
----
$transformedPropertyValue = TransformPropertyValueProcessor::transformFromObject(
    object: $yourTargetObject,
    propertyName: 'targetProperty',
    transformationArguments: ['targetProperty' => [$arrayOfArguments, $neededByYourStaticMethod]]
);
----

Remember to place original property value as the first parameter of your static method.

==== Edge cases

===== Calling the processor on generic `object`

Generic `object` instances do not have attributes. Calling a processor with a generic `object` as an argument will
always return the original property value, since no attributes are applied.

[source,php]
----
$yourTargetObject = (object)["targetProperty" => "someValue"];
$transformedPropertyValue = TransformPropertyValueProcessor::transformFromObject(
    object: $yourTargetObject,
    propertyName: 'targetProperty',
    transformationArguments: ['targetProperty' => [$arrayOfArguments, $neededByYourStaticMethod]],
);
----

Although this is an obvious waste of processing time, it is technically not an error. Keep in mind that this behavior
may change in the future with a warning or exception being thrown.

== Links

* link:../../available_attributes.adoc[Available Attributes]

