= `#[TransformPropertyValue]`
:toc:
:toclevels: 5

== Description

Use this attribute to transform the value of your property.

* Applicable to:
** Class properties

* Arguments
** `Closure $transformer` - link:https://wiki.php.net/rfc/fcc_in_const_expr[First Class Callable (PHP RFC Wiki link)].
Note that this attribute only supports using static methods.

* Repeatable: no

== Attribute Processors

=== `TransformPropertyValueProcessor`

Processor: link:../../../src/Serialization/TransformPropertyValue/TransformPropertyValueProcessor.php[`TransformPropertyValueProcessor`]

==== Methods

* `::transform(object $object, ReflectionProperty $reflectionProperty, array $context = []): mixed`
+
Returns a transformed version of a property's value by running the `Closure $transformer`. If the attribute is not
present, the original property value is returned.
+
The closure is run with the property value as the first argument, followed by `array $context`. Your static
method that does the transformation must have the following arguments: `(mixed $propertyValue, array $context)`.
+
You can use the information passed inside the `$context` in your static method.

==== Usage

===== Basic example

Apply the attribute to a property:

[source,php]
----
#[TransformPropertyValue(YourNameTransformingClass::applyPrefix(...))]
public int $yourProperty;
----

When you need to transform the value of your property, call:

[source, php]
----
$transformedPropertyValue = TransformPropertyValueProcessor::transform(
    object: $yourObject,
    reflectionProperty: new \ReflectionProperty($yourObject, 'yourPropertyName'),
    context: ['prefix' => 'somePrefix_'],
);
----

Your static method should look something like this:

[source,php]
----
public static function applyPrefix(string $originalValue, array $context): string {
    return $context['prefix']. $originalValue;
}
----

== Links

* link:../../available_attributes.adoc[Available Attributes]

