= `#[TransformPropertyName]`
:toc:
:toclevels: 5

== Description

Use this attribute to transform a name of your property during serialization.

* Applicable to:
** Class properties

* Arguments
** `Closure $transformer` - link:https://wiki.php.net/rfc/fcc_in_const_expr[First Class Callable (PHP RFC Wiki link)].
Note that this attribute only supports using static methods.

* Repeatable: no

== Attribute Processors

=== `TransformPropertyNameProcessor`

Processor: link:../../../src/Serialization/TransformPropertyName/TransformPropertyNameProcessor.php[`TransformPropertyNameProcessor`]

==== Methods

* `::transform(ReflectionProperty $reflectionProperty, array $context = []): string`
+
Returns a transformed version of a property's name by running the `Closure $transformer`. If the attribute is not
present, the original property name is returned.
+
The closure is run with the property name as the first argument, followed by `array $context`. Your static
method that does the transformation must have the following arguments: `(string $propertyName, array $context)`.
+
You can use the information passed inside the `$context` in your static method.

==== Usage

===== Basic example

Apply the attribute to a property:

[source,php]
----
#[TransformPropertyName(YourNameTransformingClass::applyPrefix(...))]
public int $yourProperty;
----

When you need to transform the name of your property, call:

[source,php]
----
$transformedPropertyName = TransformPropertyNameProcessor::transform(
    reflectionProperty: new \ReflectionProperty(TargetClass::class, 'targetProperty'),
    context: ['prefix' => 'somePrefix_']
);
----

Your static method should look something like this:

[source,php]
----
public static function applyPrefix(string $propertyName, array $context): string {
    return $context['prefix']. $propertyName;
}
----

== Links

* link:../../available_attributes.adoc[Available Attributes]
