= `#[ValidateProperty]`
:toc:
:toclevels: 5

== Description

Use this attribute to validate the value of your property.

* Applicable to:
** Class properties

* Arguments
** `Closure $transformer` - link:https://wiki.php.net/rfc/fcc_in_const_expr[First Class Callable (PHP RFC Wiki link)].
Note that this attribute only supports using static methods.

* Repeatable: no

== Attribute Processors

=== `ValidatePropertyProcessor`

Processor: link:../../../src/Validation/ValidateProperty/ValidatePropertyProcessor.php[`ValidatePropertyProcessor`]

`ValidatePropertyProcessor` supports two flavors of validation results:

* validations that return `true` on success and `false` on failure;
* validations that are silent on success and throw an exception on failure;

==== Methods

* `::validateWithBoolResult(object $object, ReflectionProperty $reflectionProperty, array $context = []): ?bool`
+
Use this method to perform a property validation with a boolean result. If the attribute is not present, null is
returned.
+
The closure is run with the property value as the first argument, followed by `$context`. Your static method
that performs validation must have the following arguments: `(mixed $propertyValue, array $context)`.
+
You can use the information passed inside the `$context` in your static method.

* `validateWithVoidResult(object $object, ReflectionProperty $reflectionProperty, array $context = []): void`
+
Use this method to process a property validation with a void result. If the attribute is not present, nothing happens
(validation skipped).
+
The closure is run with the property value as the first argument, followed by `$context`. Your static method
that performs validation must have the following arguments: `(mixed $propertyValue, array $context)`.
+
You can use the information passed inside the `$context` in your static method.

==== Usage

===== Basic example

Apply the attribute to a property:

[source,php]
----
#[ValidateProperty(YourValidationClass::yourStaticMethod(...))]
public int $yourProperty;
----

When you need to validate the value of your property, call:

[source, php]
----
$validationResult = ValidatePropertyProcessor::validateWithBoolResult(
    object: $yourTargetObject,
    reflectionProperty: new \ReflectionProperty($yourTargetObject, 'yourPropertyName'),
    context: ['compareTo' => 5]
);
----

or:

[source,php]
----
try {
    ValidatePropertyProcessor::validateWithVoidResult(
        object: $yourTargetObject,
        reflectionProperty: new \ReflectionProperty($yourTargetObject, 'yourPropertyName'),
        context: ['compareTo' => 5]
    );
} catch (Exception $exception) {
    // process your validation exception here
}
----

Your static method should look something like this (`void` example):

[source,php]
----
public static function yourValidationMethod(mixed $propertyValue, array $context): void
{
    if ($propertyValue <= $context['compareTo']) {
        throw new SampleException('Value must be larger than ' . $context['compareTo']);
    }
}
----

== Links

* link:../../available_attributes.adoc[Available Attributes]